version: "3"

services:
  dtl:
    image: metisdao/data-transport-layer:20230713210754
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      URL: https://metis-us-east-2-goerli.s3.us-east-2.amazonaws.com/addresses.json
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: ${ETHEREUM_RPC_ENDPOINT:?Set Ethereum rpc endpoint first}
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: "https://goerli.gateway.metisdevops.link"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: "false"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: "true"
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: "599"
      DATA_TRANSPORT_LAYER__DB_PATH: /data/db
      DATA_TRANSPORT_LAYER__SERVER_PORT: "7878"
      DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: "1000"
      DATA_TRANSPORT_LAYER__CONFIRMATIONS: "0"
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: "1000"
      DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: "1000"
      DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: "true"
      DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: "0.0.0.0"
    expose:
      - 7878
    volumes:
      - ./chaindata/dtl:/data
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  l2geth:
    image: metisdao/l2geth:20230713220744
    entrypoint: [ "sh", "/scripts/geth.sh" ]
    restart: unless-stopped
    stop_grace_period: 2m
    env_file:
      - ./geth.env
    environment:
      CHAIN_ID: 599
      NETWORK_ID: 599
      URL: https://metis-us-east-2-goerli.s3.us-east-2.amazonaws.com/addresses.json
      L2GETH_GENESIS_URL: https://metis-us-east-2-goerli.s3.us-east-2.amazonaws.com/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      L2_URL: https://goerli.gateway.metisdevops.link
      SEQUENCER_CLIENT_HTTP: https://goerli.gateway.metisdevops.link
      ETH1_CTC_DEPLOYMENT_HEIGHT: 7489400
      TARGET_GAS_LIMIT: 9000000
    volumes:
      - ./chaindata/l2geth:/root/.ethereum
      - ./scripts:/scripts
    ports:
      - 8546:8546
      - 8545:8545
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
